package HelloApp;


/**
* HelloApp/HelloPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 2014년 4월 13일 일요일 오전 1시 04분 47초 KST
*/

public class HelloObjectAdapterTie extends HelloObjectAdapter
{

  // Constructors

  public HelloObjectAdapterTie ( HelloApp.IHelloOperations delegate ) {
      this._impl = delegate;
  }
  public HelloObjectAdapterTie ( HelloApp.IHelloOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public HelloApp.IHelloOperations _delegate() {
      return this._impl;
  }
  public void _delegate (HelloApp.IHelloOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String sayHello ()
  {
    return _impl.sayHello();
  } // sayHello

  public void shutdown ()
  {
    _impl.shutdown();
  } // shutdown

  private HelloApp.IHelloOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class HelloPOATie
