package HelloApp;


/**
* HelloApp/HelloHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 2014년 4월 13일 일요일 오전 1시 04분 47초 KST
*/

abstract public class HelloDao
{
  private static String  _id = "IDL:HelloApp/Hello:1.0";

  public static void insert (org.omg.CORBA.Any a, HelloApp.IHello that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HelloApp.IHello extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (HelloApp.HelloDao.id (), "Hello");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HelloApp.IHello read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (HelloMarshaller.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HelloApp.IHello value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static HelloApp.IHello narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HelloApp.IHello)
      return (HelloApp.IHello)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HelloApp.HelloMarshaller stub = new HelloApp.HelloMarshaller ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static HelloApp.IHello unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HelloApp.IHello)
      return (HelloApp.IHello)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HelloApp.HelloMarshaller stub = new HelloApp.HelloMarshaller ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
