package HelloApp;

/**
* HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 2014년 4월 13일 일요일 오전 1시 04분 47초 KST
*/

public final class HelloProxy implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.IHello value = null;

  public HelloProxy ()
  {
  }

  public HelloProxy (HelloApp.IHello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.HelloDao.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.HelloDao.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.HelloDao.type ();
  }

}
