package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 2014년 4월 13일 일요일 오전 1시 04분 47초 KST
*/

public interface IHelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
